version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123  # Contrase침a del usuario root (c치mbiala en producci칩n)
      MYSQL_DATABASE: mydatabase  # Nombre de la base de datos por defecto
      MYSQL_USER: admin  # Usuario adicional
      MYSQL_PASSWORD: admin123  # Contrase침a del usuario adicional
    ports:
      - "3307:3306"  # Expone el puerto 3306 en el contenedor como 3307 en la m치quina host
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos

volumes:
  mysql_data:

# 游댳 Para conectarte desde la terminal:
# docker exec -it mysql-container mysql -u admin -p
