version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin  # Usuario de la base de datos
      POSTGRES_PASSWORD: admin123  # Contraseña (cámbiala en un entorno seguro)
    ports:
      - "5433:5432"  # Exponer el puerto 5432 en el contenedor como 5433 en la máquina host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

volumes:
  postgres_data:

# 🔹 Para conectarte desde la terminal:
# docker exec -it postgres-container psql -U admin -W
